name: My First Workflow

on: push

jobs:
    first_job:
          runs-on: ubuntu-latest
          steps:
              - name : welcome message
                runs: echo "my first git hub actions job"

              - name : list files
                runs: ls

              - name: Read Files
                run: cat README.md