name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: list and read file
        run: |
          echo "my first git hub actions job"
          ls -ltr -a
          cat README.md

      - name: Generate ASCII key artwork
        run: cowsay -f dragon "Run for cover, I am a Dagon... RAWR" >> dragon.txt

      # - name: list files
      #   run: ls

      # - name: Read Files
      #   run: cat README.md